---
on:
  - push

jobs:
  terraform:
    name: terraform
    env:
      VAULT_ADDR: "http://vault-not:8200"
      VAULT_TOKEN: "simple"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: default
      max-parallel: 3
    services:
      vault:
        image: vault
        env:
          VAULT_DEV_ROOT_TOKEN_ID: "simple"
        ports:
          - 8200:8200
      cassandra:
        image: robertdebock/cassandra
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: terraform init
        uses: robertdebock/terraform-action@1.1.2
        with:
          directory: ./examples/${{ matrix.config.name }}
      - name: Run terraform validate
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: validate
          directory: ./examples/${{ matrix.config.name }}
      - name: Run terraform plan
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: plan
          directory: ./examples/${{ matrix.config.name }}
      - name: Run terraform apply
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: apply
          directory: ./examples/${{ matrix.config.name }}
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
REV
      - name: Run terraform destroy
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: destroy
          directory: ./examples/${{ matrix.config.name }}
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
        if: ${{ always() }}
